version: 2

jobs:
  build: &build
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          name: Install gems
          command: bundle install
      - run:
          name: RSpec
          command: rspec
  ruby-2.4:
    <<: *build
    docker:
      - image: circleci/ruby:2.4

  ruby-2.5:
    <<: *build
    docker:
      - image: circleci/ruby:2.5

workflows:
  version: 2
  build-multiple-rubies:
    jobs:
      - ruby-2.4
      - ruby-2.5
